# Generated by Django 4.0.4 on 2022-04-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAndPlan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='data',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
