# Generated by Django 4.0.4 on 2022-04-29 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAndPlan', '0005_alter_plan_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAndPlan.categoryplan'),
        ),
    ]
