# Generated by Django 4.0.4 on 2022-04-30 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAndPlan', '0007_alter_plan_plan_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAndPlan.areacircle')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAndPlan.operator')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAndPlan.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
