# Generated by Django 4.0.4 on 2022-04-30 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAndPlan', '0008_recharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recharge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link='email', to=settings.AUTH_USER_MODEL),
        ),
    ]
