# Generated by Django 4.0.4 on 2022-05-01 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAndPlan', '0009_alter_recharge_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacircle',
            name='area',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='operator_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAndPlan.areacircle', to_field='area'),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAndPlan.operator', to_field='operator_name'),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAndPlan.plan', to_field='price'),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
