# Generated by Django 4.0.4 on 2022-05-02 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAndPlan', '0010_alter_areacircle_area_alter_operator_operator_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recharge',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_detail', to='userAndPlan.plan', to_field='price'),
        ),
    ]
