# Generated by Django 4.0.4 on 2022-05-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAndPlan', '0011_alter_recharge_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
